name: Build
on:
  push:
    branches:
      - main
      - "chore/**"
      - "feature/**"
      - "fix/**"

jobs:
  sonarqube:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Debug SONAR_TOKEN presence
        run: |
          if [ -z "${{ secrets.SONAR_TOKEN }}" ]; then
            echo "SONAR_TOKEN is MISSING"
            exit 1
          else
            echo "SONAR_TOKEN is PRESENT"
          fi
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}